# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/loginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Войти в Яндекс")
        Dialog.resize(274, 256)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.loginInput = QtWidgets.QLineEdit(Dialog)
        self.loginInput.setWhatsThis("")
        self.loginInput.setObjectName("loginInput")
        self.verticalLayout_2.addWidget(self.loginInput)
        self.passinput = QtWidgets.QLineEdit(Dialog)
        self.passinput.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.passinput.setObjectName("passinput")
        self.verticalLayout_2.addWidget(self.passinput)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.loginbutton = QtWidgets.QPushButton(Dialog)
        self.loginbutton.setObjectName("loginbutton")
        self.verticalLayout.addWidget(self.loginbutton)
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 33))
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Войдите в Яндекс"))
        self.loginInput.setPlaceholderText(_translate("Dialog", "Логин или e-mail"))
        self.passinput.setPlaceholderText(_translate("Dialog", "Пароль"))
        self.loginbutton.setText(_translate("Dialog", "Войти"))
